# Single model test configuration - Chatbot
test_duration: 600
target_rps: 2
request_timeout: 2000
seed: 42

tokenizer:
  name: "Qwen/Qwen3-0.6B"
  trust_remote_code: false

models:
  - name: "Chatbot"
    type: "llm"
    endpoint: "http://127.0.0.1:48000/v1/completions"
    input_len: 900
    output_len: 300
    range_ratio: 0.0
    temperature: 0.7
    stream: true
    ignore_eos: true

scenarios:
  round_robin:
    enabled: false

  zipfian:
    enabled: false
    weights: [1.0]

  bursty:
    enabled: false

  single_model:
    enabled: true

  rag:
    enabled: false
    weights: [100]